const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true}),p=await b.newPage();
for(const width of [320,375,390,430]){await p.setViewportSize({width,height:900});await p.goto('http://localhost:8000/index.html');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Home overflow ${width}`);console.log('Home width PASS',width);}
async function tabTo(href){for(let i=0;i<250;i++){await p.keyboard.press('Tab');if(await p.evaluate(()=>document.activeElement?.tagName==='SUMMARY'&&!document.activeElement.parentElement.open))await p.keyboard.press('Enter');if(await p.evaluate(h=>document.activeElement?.getAttribute('href')===h,href)){assert(await p.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle!=='none'));await p.keyboard.press('Enter');await p.waitForTimeout(400);return;}}throw Error('Keyboard unreachable '+href)}
await p.setViewportSize({width:1280,height:900});await p.goto('http://localhost:8000/index.html');await tabTo('iol-catalog.html');
// Native details: enter expands with browser-managed accessibility state.

await tabTo('iol-detail.html?model=TFNT00');await p.waitForSelector('#source-list .source-card');await tabTo('iol-comparison.html');console.log('Keyboard Home → Catalog → Detail → Comparison PASS');
for(const url of ['index.html','iol-catalog.html','iol-comparison.html','scene-library.html','iol-detail.html?model=DIB00']){await p.goto('http://localhost:8000/'+url);await p.waitForTimeout(600);const missing=await p.locator('input,select,textarea').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&!e.labels?.length&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')).map(e=>e.id));assert.deepEqual(missing,[],url+' unlabeled inputs');}
await p.goto('http://localhost:8000/iol-detail.html?model=DIB00');await p.waitForSelector('#source-E2');assert((await p.locator('#source-E2').innerText()).includes('37069559'));assert((await p.locator('#source-E3').innerText()).includes('PMC8046615'));assert((await p.locator('#evidence-disclaimer').innerText()).includes('E2 — Source verified'));assert(!(await p.locator('body').innerText()).includes('保持 null'));
const toggle=p.locator('#source-E2 .source-verification summary');await toggle.focus();const was=await toggle.evaluate(e=>e.parentElement.open);await p.keyboard.press('Enter');assert.equal(await toggle.evaluate(e=>e.parentElement.open),!was);console.log('Source identifiers, dynamic verification, native keyboard disclosure, form labels PASS');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
