/* Read-only validation. Run: node scripts/validate-data.cjs */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const sandbox={window:{}};for(const file of ['evidence-routing.js','evidence-utils.js','defocus-calculator.js'])vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox);
const {EvidenceRouting:R,EvidenceUtils:U,DefocusCalculator:C}=sandbox.window;
function walk(dir){for(const e of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(p.endsWith('.json'))read(p);}}walk('data');
const catalog=read('data/taiwan-iol-catalog.json'),index=read('data/evidence/index.json'),targets=[...new Set([...Object.entries(index).filter(([k])=>k!=='products').map(([,v])=>v),...Object.values(index.products||{})])];
const records=targets.map(p=>{assert(p.startsWith('data/evidence/')&&!p.includes('..'),'Invalid evidence path');return read(p)}),warnings=[];
for(const r of records){assert(!/demo|placeholder/i.test(r.dataStatus),'Formal record is placeholder');const ids=new Set();for(const s of r.sources||[]){assert(s.label&&!ids.has(s.label),'Duplicate/missing source ID');ids.add(s.label);if(!s.title)warnings.push(`${r.recordId}/${s.label}: missing source title`);assert(s.sourceType||s.source_type,'Missing source type');const v=s.verification;assert(v&&['verified_primary_or_official_source','partially_verified','not_independently_verified',null].includes(v.status),'Invalid verification');assert(Object.hasOwn(v,'verified_date')&&Array.isArray(v.verified_against)&&Object.hasOwn(v,'notes'),'Incomplete verification');if(!s.sourceIdentifier&&!s.DOI&&!s.PMID)warnings.push(`${r.recordId}/${s.label}: no structured identifier (may be an official document)`);const seen=new Set();for(const p of s.defocus_points||[]){assert(typeof p.defocus_D==='number'&&Number.isFinite(p.defocus_D)&&!seen.has(p.defocus_D));seen.add(p.defocus_D);for(const k of ['mean_logMAR','SD_logMAR'])assert(p[k]===null||typeof p[k]==='number'&&Number.isFinite(p[k]));assert(p.SD_logMAR===null||p.SD_logMAR>=0);assert(p.source===s.label);}}
for(const [k,refs] of Object.entries(r.parameterSourceMap||{}))for(const id of refs)assert(ids.has(id),`${k}: unmapped source ${id}`);
for(const p of r.clinicalParameters||[])if(p.value&&typeof p.value==='object'&&Object.hasOwn(p.value,'percentage'))assert(p.value.percentage===null||typeof p.value.percentage==='number'&&p.value.percentage>=0&&p.value.percentage<=100);
}
const mapping=catalog.map(p=>{const target=R.path(index,p),r=target?read(target):null;if(r)assert(R.matches(r,p),'Invalid product mapping '+p.model_number);return {model:p.model_number,key:p.product_key||null,target,detail:R.detail(p)}});
const snapshot={};for(const r of records){const p=catalog.find(p=>R.matches(r,p));assert(p,'Orphan evidence');snapshot[r.recordId]=Array.from(U.classify(p,r,records),c=>c.status);}
const expected=read('tests/coverage.snapshot.json');assert.deepEqual(snapshot,expected,'Coverage regression: inspect before updating snapshot');
const pan=records.find(r=>r.product.model_number==='TFNT00');for(const [d,method] of [[40,'direct published point'],[70,'website-derived linear interpolation'],[100,'direct published point']]){const result=C.calculate(d,pan);assert(!result.error);assert.equal(result.method,method);if(d===70)assert.equal(result.sd,null);}assert(C.calculate(20,pan).error);for(const r of records.filter(r=>r!==pan))for(const d of [40,66,70])assert(C.calculate(d,r).error,'Non-numerical product estimated');
// Unknown and explicit zero remain distinct in classification; no fixture supplies medical values.
const placeholder={dataStatus:'DEMO',sources:[{label:'placeholder',title:'placeholder',sourceType:'placeholder',defocus_points:[{defocus_D:0,mean_logMAR:0}]}]};assert.equal(U.classify({},placeholder,[])[1].status,'Not structured yet');
console.log(JSON.stringify({result:'PASS',catalogRecords:catalog.length,evidenceFiles:targets.length,mapping,coverage:snapshot,warnings},null,2));
